version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.7.3
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 0.0.0.0:5000:5000
    command: python src/server.py
    restart: on-failure

  dbdata:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: $APPLICATION_POSTGRES_PW
      POSTGRES_USER: $APPLICATION_POSTGRES_USER
      POSTGRES_DB: $APPLICATION_POSTGRES_DB
    volumes_from:
      - dbdata
    restart: on-failure
    ports:
      - 127.0.0.1:5432:5432

  testserver:
    env_file: .env
    image: python:3.7.3
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:9.6
