"""empty message

Revision ID: 1e78d894f118
Revises: 88a3ffd03b5a
Create Date: 2020-11-21 01:53:13.130081

"""

# revision identifiers, used by Alembic.
revision = '1e78d894f118'
down_revision = '88a3ffd03b5a'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('achievements_rate', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('trivia_rate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'trivia_rate')
    op.drop_column('user', 'achievements_rate')
    op.drop_column('trivia', 'completed')
    # ### end Alembic commands ###
