"""added achievements

Revision ID: 249eca898a31
Revises: 6bc7d13aa575
Create Date: 2020-11-20 12:48:09.409072

"""

# revision identifiers, used by Alembic.
revision = '249eca898a31'
down_revision = '7624bed54ba3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('long_description', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.Column('bg_image_src', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement')
    # ### end Alembic commands ###
