"""empty message

Revision ID: 38c4857b223b
Revises: fff6fd15cb11
Create Date: 2020-11-20 23:36:56.790075

"""

# revision identifiers, used by Alembic.
revision = '38c4857b223b'
down_revision = 'fff6fd15cb11'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
