"""added obtained model for achievements

Revision ID: 6fa53ebdac2e
Revises: 249eca898a31
Create Date: 2020-11-20 12:51:18.146518

"""

# revision identifiers, used by Alembic.
revision = '6fa53ebdac2e'
down_revision = '249eca898a31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obtained',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.oid'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obtained')
    # ### end Alembic commands ###
