"""empty message

Revision ID: 7e0b73c24b2f
Revises: c1b0b4199590
Create Date: 2020-11-21 02:27:35.340932

"""

# revision identifiers, used by Alembic.
revision = '7e0b73c24b2f'
down_revision = 'c1b0b4199590'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
