"""empty message

Revision ID: 88a3ffd03b5a
Revises: c4dccb067112
Create Date: 2020-11-21 00:23:41.046122

"""

# revision identifiers, used by Alembic.
revision = '88a3ffd03b5a'
down_revision = 'c4dccb067112'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
