"""empty message

Revision ID: c1b0b4199590
Revises: 1e78d894f118
Create Date: 2020-11-21 02:11:49.359561

"""

# revision identifiers, used by Alembic.
revision = 'c1b0b4199590'
down_revision = '1e78d894f118'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_answer', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('submitted_answer', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'submitted_answer', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submitted_answer', type_='foreignkey')
    op.drop_column('submitted_answer', 'question_id')
    op.drop_column('submitted_answer', 'created_at')
    # ### end Alembic commands ###
