"""empty message

Revision ID: c4dccb067112
Revises: ce8f960e688c
Create Date: 2020-11-21 00:05:12.243678

"""

# revision identifiers, used by Alembic.
revision = 'c4dccb067112'
down_revision = 'ce8f960e688c'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivias_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('trivia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivia.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trivias_questions')
    # ### end Alembic commands ###
