"""empty message

Revision ID: ca5ac82cc6ad
Revises: 7e0b73c24b2f
Create Date: 2020-11-21 02:49:47.186110

"""

# revision identifiers, used by Alembic.
revision = 'ca5ac82cc6ad'
down_revision = '7e0b73c24b2f'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('first_player_score', sa.Integer(), nullable=False))
    op.add_column('trivia', sa.Column('second_player_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'second_player_score')
    op.drop_column('trivia', 'first_player_score')
    # ### end Alembic commands ###
