"""empty message

Revision ID: ce8f960e688c
Revises: 38c4857b223b
Create Date: 2020-11-21 00:00:55.781110

"""

# revision identifiers, used by Alembic.
revision = 'ce8f960e688c'
down_revision = '38c4857b223b'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trivia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivia.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trivia', sa.Column('achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trivia', 'achievement', ['achievement_id'], ['id'])
    op.drop_column('trivia', 'is_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trivia', type_='foreignkey')
    op.drop_column('trivia', 'achievement_id')
    op.drop_table('submitted_answer')
    # ### end Alembic commands ###
