"""empty message

Revision ID: d817da1687e6
Revises: 6fa53ebdac2e
Create Date: 2020-11-20 20:08:25.961688

"""

# revision identifiers, used by Alembic.
revision = 'd817da1687e6'
down_revision = '6fa53ebdac2e'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trivia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('second_player_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['second_player_id'], ['user.oid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_right', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('trivia')
    op.drop_table('question')
    # ### end Alembic commands ###
