"""empty message

Revision ID: fff6fd15cb11
Revises: d817da1687e6
Create Date: 2020-11-20 23:02:02.368998

"""

# revision identifiers, used by Alembic.
revision = 'fff6fd15cb11'
down_revision = 'd817da1687e6'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('is_test', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'is_test')
    # ### end Alembic commands ###
